[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Robin.Wang", email = "3Jg$94sbQ@q1"},
]
dependencies = [
    "django>=4.2.6",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

