# Generated by Django 4.2.6 on 2023-10-09 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver", models.CharField(max_length=10, verbose_name="收件人")),
                ("address", models.CharField(max_length=100, verbose_name="地址")),
                ("postcode", models.CharField(max_length=6, verbose_name="邮编")),
                (
                    "receiver_mobile",
                    models.CharField(max_length=11, verbose_name="手机号"),
                ),
                ("tag", models.CharField(max_length=10, verbose_name="标签")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认地址")),
                ("is_delete", models.BooleanField(default=False, verbose_name="伪删除")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "db_table": "users_address",
            },
        ),
    ]
