"""
Django settings for dashop project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

DB_PASSWORD = os.getenv("DB_PASSWORD")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v2k$_pxsz5d)q38nrxdcxmg)li9%wbx5+b2@2(_x@n3*#pa2*x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "users",
    "goods",
    "carts",
    "orders",
    "pays",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dashop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dashop.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': DB_PASSWORD,
        'NAME': 'dashop',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------跨域配置-------------- #
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:7000",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:7000",
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

CORS_PREFLIGHT_MAX_AGE = 3600 * 24  # 一天

# -------------jwt配置-------------- #
JWT_TOKEN_KEY = os.getenv("JWT_TOKEN_KEY")

# -------------发送邮件设置-------------- #
# 1.固定写法
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 2.腾讯QQ邮箱 SMTP 服务器地址
EMAIL_HOST = 'smtp.qq.com'
# 3.SMTP服务的端口号
EMAIL_PORT = 25
# 4.发送邮件的QQ邮箱
EMAIL_HOST_USER = os.getenv("MAIL_HOST")
# 5.在QQ邮箱->设置->帐户->“POP3/IMAP......服务” 里得到的在第三方登录QQ邮箱授权码
EMAIL_HOST_PASSWORD = os.getenv("MAIL_TOKEN")
# 与SMTP服务器通信时，是否启动TLS链接(安全链接)默认false
EMAIL_USE_TLS = True

# -------------缓存配置-------------- #
CACHES = {
    # db1:存储邮件激活随机数
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # db2:存储短信验证码
    "sms": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # db3:商品首页展示缓存
    "index": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "",
        }
    },
    # db4:商品详情页缓存
    "detail": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "",
        }
    },
    # db5:购物车数据
    "carts": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/5",
        # 默认是300秒,设置为None表示永久存储,永不过期
        "TIMEOUT": None,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "",
        }
    },
}

# -------------短信接口配置-------------- #
SMS_ACCOUNT_SID = os.getenv("SMS_ACCOUNT_SID")
SMS_TOKEN = os.getenv("SMS_TOKEN")
SMS_APP_ID = os.getenv("SMS_APP_ID")

# -------------微博配置-------------- #
WEIBO_CLIENT_ID = os.getenv("WEIBO_APP_KEY")
WEIBO_CLIENT_SECRET = os.getenv("WEIBO_APP_SECRET")
WEIBO_REDIRECT_URI = os.getenv("WEIBO_REDIRECT_URI")

# -------------静态路由---------------#
# http://127.0.0.1:8000/media/sku/1.png
MEDIA_URL = "/media/"
# /project/dashop/media
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -------------页面图片地址------------#
PIC_URL = "http://127.0.0.1:8000/media/"

# ------------- 支付宝支付------------#
ALIPAY_APPID = os.getenv("ALIPAY_APP_ID")
ALIPAY_NOTIFY_URL = "http://127.0.0.1:8000/v1/pays/notify_url"
ALIPAY_RETURN_URL = "http://127.0.0.1:8000/v1/pays/return_url"
# project/dashop/utils/key_files/
ALIPAY_KEY_DIR = os.path.join(BASE_DIR, "utils/key_files/")
